- hosts: datanode
  vars_files:
     - datanode_var.yml
  tasks:
  - name: "Copying the hadoop File"
    copy:
     src: "{{ hadoop_path }}"
     dest: "/root/"
    register: hadoop
  - name: "Copying the JDK File"
    copy:
     src: "{{ jdk_path }}"
     dest: "/root/"
    register: java
  - name: "Installing Jdk"
    shell: "rpm -ivh {{ jdk_software }}"
    when: java.changed!=false
  - name: "Installing Hadoop"
    shell: "rpm -ivh {{ hadoop_software }}  --force"
    when: hadoop.changed!=false
  - name: "Copying the core-site.xml file"
    template:
      src: "{{ core_site }}"
      dest: "/etc/hadoop/"
  - name: "Copying the hdfs-site.xml file"
    copy:
      src: "{{ hdfs_site }}"
      dest: "/etc/hadoop/"
  - name: "Deleting the directory"
    shell: "{{ directory_delete }}"
    ignore_errors: yes
  - name: "Creating a directory"
    file:
      state: directory
      path: "{{ directory_path }}"
  - name: "Formatting the directory"
    shell: "echo Y |  hadoop namenode -format"



  - name: "Starting the datanode"
    shell: "{{ start_datanode }}"
    ignore_errors: yes
    register: hadoop_started

  - name: "Started hadoop"
    debug:
     var: hadoop_started.stdout

  - name: "Java Process"
    shell: "{{ run_jps }}"
    register: jps

  - name: "Java Process"
    debug:
     var: jps.stdout
